delete from "Program" Cascade;
delete from "Source" Cascade;
delete from "Account" Cascade;
delete from "ProgramRelationSource" Cascade;
delete from "ProgramComment" Cascade;
delete from "ProgramCommentRelation" Cascade;
delete from "Jobs" Cascade;
delete from "Alchol" Cascade;
delete from "Language" Cascade; 
delete from "UserCategories" Cascade;
delete from "Categories" Cascade;
delete from "AlcholLike" Cascade;
delete from "UserCategorisedPrograms" Cascade;
delete from "Extension" Cascade;
SELECT setval('"Account_userid_seq"',1,false);
SELECT setval('"Categories_categoryid_seq"',1,false);
SELECT setval('"Program_programid_seq"',1,false);
SELECT setval('"Source_fileid_seq"',1,false);
SELECT setval('"UserCategories_categoryid_seq"',1,false);